//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<ApartmentDemands> ApartmentDemands { get; set; }
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<HouseDemands> HouseDemands { get; set; }
        public virtual DbSet<Houses> Houses { get; set; }
        public virtual DbSet<LandDemands> LandDemands { get; set; }
        public virtual DbSet<Lands> Lands { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
    }
}
